actividad(id, nombre, descripcion, url_icon)
agenda_actividad(id, id_usuario, id_actividad, hora, fecha, lugar)
centro_emergencia(id, nombre, telefono, direccion, id_ciudad)
ciudad(id, nombre)
contacto(id, nombre, telefono, url_foto, id_usuario)
mensajes_motivacionales(id, nombre, descripcion, autor)
tecnica_relajacion(id, nombre, autor, url_recurso)
usuario(id, nombre, id_ciudad)
visualiza_mensaje(id, id_mensaje, id_usuario)
visualiza_tecnica(id, id_relajacion, id_usuario)
